### ISSUE TITLE
Selecting in live view mode bugged

### ISSUE THREAD

**Issue by NathanReed2** [RenolY2/battalion-level-editor#18]
Use the selection box in live view and you can't unselect things without leaving live view mode.

**Comment by NathanReed2** [comment]
same with live edit

**Comment by RenolY2** [comment]
The most likely cause for this is shift getting stuck due to clicking out of the window. As a workaround press shift again to fix selection.

**Comment by RenolY2** [comment]
Closed and reopened with more accurate title/info:
https://github.com/RenolY2/battalion-level-editor/issues/18
